# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems:                 [jekyll-paginate]
# Setup
title:               片虚
tagline:             'Like a void leaf'
description:         'Like a void leaf'
url:                 http://viodleaf.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
